version: '3'

services:
  app:
    build: .
    container_name: api-rn2
    command: python manage.py runserver 0.0.0.0:5000
    volumes:
      - .:/home/django/app
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres
    container_name: db-rn2
    tty: true
    environment:
      - POSTGRES_DB=redenativa
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - iniciando-django-pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-rn2
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@user.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - "9000:80"

volumes:
  iniciando-django-pgdata:
    external: true
